name: New CFE workflow notifications
on:
  push:
    branches:
      - "new-cfe-workflow-notifications"
  issues:
    types: [labeled]
  workflow_dispatch:
    inputs:
      ref:
        description: 'Branch reference (e.g. refs/heads/main)'
        required: false
        default: ''

permissions:
  issues: write
  contents: write

jobs:
  notify-cfe-created:
    # if: github.event.label.name == 'code freeze exception'
    runs-on: ubuntu-20.04
    steps:
      - name: Debug GitHub Context
        run: |
          echo "${{ toJson(github) }}"

      - name: Notify Slack
        uses: archive/github-actions-slack@v2.0.0
        id: notify
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.CODE_FREEZE_BOT_TOKEN }}
          slack-channel: "naman-test"
          slack-text: |
            Test
          slack-optional-unfurl_links: false
          slack-optional-unfurl_media: false
        continue-on-error: true

      - name: Close the issue
        if: github.event_name == 'issues'
        run: gh issue close --comment "Closing issue. https://github.com/${{ github.repository }}/issues/${{ github.event.issue.number }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
